### ISSUE TITLE
Sanity graphql-deploy error

### ISSUE THREAD

**Issue by rafaelderolez** [good-idea/sane-shopify#24]
I'm getting the following error when running `sanity graphql-deploy`.
Anyone else encounter the same thing?

```
➜  studio git:(master) npm run graphql-deploy

> sanity-gatsby-blog-studio@1.0.1 graphql-deploy /Users/raf/code/gatsby-shopify-sanity-alpha/studio
> sanity graphql deploy --playground

✖ Generating GraphQL schema
/Users/raf/code/gatsby-shopify-sanity-alpha/studio/node_modules/@sane-shopify/sanity-plugin/lib/index.js:1
import { createElement, Fragment, Component } from 'react';
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at compileFunction (<anonymous>)
```

**Comment by good-idea** [comment]
It looks like this might be an issue on my end for improperly bundling the package. I'll be getting back to work on this early next week and will look into this.

**Comment by philly-d** [comment]
I'm running into this, too. I think it's due to the plugin needing to be ES5-compatible. See: https://www.sanity.io/docs/plugins#plugins-within-node-modules-86ff8e7a3286 (seems only local sanity plugins are automatically run through Babel).
I'm not familiar with Rollup so there's probably unintentional consequences here I'm not considering, but just changing the output format from 'es' to 'cjs' here and rebuilding the library worked for me: https://github.com/good-idea/sane-shopify/blob/master/packages/sanity-plugin/rollup.config.js#L9.
This is a really awesome project @good-idea -- thanks so much for open-sourcing it!
