### ISSUE TITLE
[Request] Multiple Shopify stores

### ISSUE THREAD

**Issue by benjaminsehl** [good-idea/sane-shopify#46]
Hey there — 

I'm in the situation of having multiple instances of Shopify — they're exactly the same, but ideally I'd manage the content in one place. So for products, I need to have the product id's from both stores link.

Would that be a remote possibility, even with some moderate/heavy modification? 

Cheers

**Comment by good-idea** [comment]
This is interesting! As far as work goes, it might not be too crazy. It would mean storing an array of storefront names + access tokens, and modifying how the dashboard plugin works. The dashboard UI is going to get a full refactor anyway, might as well look into this ahead of time.

I'll tag it as a 1.0 feature for now - but I will need to consider it some more and dig into the details before confirming that it will happen. Tracking it here in a separate issue so I can see the cute "tasks complete" checkbox on the issue summary:  https://github.com/good-idea/sane-shopify/issues/47

On the frontend, you would need to use separate carts for each storefront. This is outside of the scope of this project so that doesn't really matter here --- but I'm curious about how you might handle this?

**Comment by benjaminsehl** [comment]
Never replied here, but in this instance the two storefronts are for different locales — so I would have a country picker, which I'd then use to select the appropriate IDs and build out the cart. That was the thought anyway! My plan though actually is to use this for everything _but_ the product/cart/checkout pages. Linking out to subdomains for the two stores for that piece — potentially rendering any extra Sanity content client side on those pages.
