### ISSUE TITLE
feature: multiple storefronts

### ISSUE THREAD

**Issue by good-idea** [good-idea/sane-shopify#47]
Re: https://github.com/good-idea/sane-shopify/issues/46

- [ ] Update plugin UI to be able to add, sync, & remove multiple storefronts.
- [ ] Include storefront info in all synced items
- [ ] include in sync-utils API

**Comment by benjaminsehl** [comment]
With Shopify announcing the ability to have better multi-locale controls within one Shopify store, this (for me) is less important now. There might still be a use case for this — but I'm not exactly sure what that would be, as any need for multiple stores (shortly) will likely be because of differences in product availability and content management.

**Comment by good-idea** [comment]
@benjaminsehl cool, good to know and thanks for checking in.

Another approach that someone clued me into - which I hadn't considered but is a great idea - is having a single shopify instance power multiple stores, and just separating inventory by setting up two Storefront API sales channels and marking products as visible/not visible.

I'm not sure if this is helpful regarding locales, if you're talking about different currencies. But if you're talking about different languages, there are some sanity plugins that handle this, so that could be used on top of sane-shopify.

I'm going to close this issue for now.. The overall scope of using multiple storefronts syncing to a single Sanity instance adds a bunch of complications for syncing that I won't have time to get into for now. Maybe for 2.0..

**Comment by productlabs** [comment]
I can always add this as a branch. :)

- Kevin
________________________________
